version: '3'
services:

  web:
    build: .
    ports:
      # Port Flask
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14.4-bullseye
    container_name: postgres_db_container
    ports:
      - "5432:5432"
    volumes:
      - database:/var/lib/postgresql

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nlp-review-labeler
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  database: